# Generated by Django 2.0.7 on 2019-02-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Anonymus', max_length=256)),
                ('content', models.TextField()),
                ('post_name', models.ForeignKey(on_delete=None, to='blog.Post')),
            ],
        ),
    ]
