# Generated by Django 2.0.7 on 2019-02-14 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190214_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contribute',
            field=models.CharField(default='Anonymouss', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 14, 20, 35, 37, 665428)),
        ),
    ]
