# Generated by Django 2.0.7 on 2019-02-14 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190214_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contribute',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 14, 21, 2, 44, 717302)),
        ),
    ]
