# Generated by Django 2.2.1 on 2019-08-26 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190620_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='blog_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='contribute',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 26, 15, 48, 3, 281571)),
        ),
    ]
