# Generated by Django 2.2.1 on 2019-08-26 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20190826_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contribute',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 26, 15, 48, 59, 579517)),
        ),
    ]
